### ISSUE TITLE
[feature request] Future support for the TMS9900? (if possible with minimal lib for the TI99/4A?)

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [EtchedPixels/CC6303#19]
I have seen some of your very recent development for the TMS9995.
Do you plan to also support the plain TMS9900. They almost have the set instruction set, with the TMS9995 maybe adding only 4 opcodes.
If that is the case, would you also consider adding a target for the (memory expanded) TI99/4A with very minimal input/output (as you have done for the MC-10)?

For a reference on a similar project (GCC for TI99/4A) you may find this useful:
https://atariage.com/forums/topic/164295-gcc-for-the-ti/

I have been able to use it here:
https://github.com/Fabrizio-Caruso/CROSS-LIB/blob/master/src/games/chase/makefiles.chase/Makefile.gcc_tms9900_targets

Some of the tools and crt are described in the thread above.
What I use for my project is also found here:
https://github.com/Fabrizio-Caruso/CROSS-LIB/tree/master/tools/ti99

There is also a CONIO implementation here that may be useful:
https://github.com/tursilion/libti99

**Comment by EtchedPixels** [comment]
I did play with the ti99/4a gcc initially but it was incredibly buggy.

I got a bit stuck with cc68 and tms9995 because it's got a lot of registers and despite my best efforts to make use of them the cc65 core doesn't really know how to do it. Instead see

https://github.com/EtchedPixels/pcc-tms9995-support

I have this building and running a few things. There is a bug in vararg handling (promotion of char to int for unprototyped parameters)  at the moment but otherwise it seems to be doing reasonably okay on char, integer and some long.

For the 9900 I believe the only difference would be that you don't have DIVS so would need instead to use a small helper to switch the signs as needed and use DIV.

**Comment by Fabrizio-Caruso** [comment]
Cool! I am looking forward to seeing TMS9900 and TI99/4A if you ever implement it.
I think TMS9900 is indeed close enough to require a minor adaptation.
Support for TI99/4A would just be a matter to use the CRT , to plug in an implementation for getchar and putchar and produce a cartridge (or tape) image. 
Indeed GCC for TI is not reliable and moreover it is not easy to build. I would be more than happy to ditch and use your compiler.

**Comment by Fabrizio-Caruso** [comment]
By the way, if you ever produce a TMS9900 compiler if possible with minimal support for the TI99/4A, I will test it extensively and maybe spot some bugs and give you some hopefully useful feed-back.

**Comment by EtchedPixels** [comment]
All the hooks are now there, would need someone who knows about the 99/4a to write the crt0,  set the memory map up etc

**Comment by EtchedPixels** [comment]
Probably but without knowing how things are loaded, what the memory layout is etc not a lot.

**Comment by Fabrizio-Caruso** [comment]
Most homebrew developers build cartridge images for the TI99/4A. Cassettes are possible but not common now.

If I remember well, the cartridges do not provide a contiguous directly addressable unique block of memory. It provides several 8k banks of memory. So running from the cartridge would require bank-switching  (which is close to impossible code to generate for a C compiler).
So most games and tools assume you have a 32k RAM expansion and the code is "automatically" decompressed into it.
The tools I use (see my links) should create cartridge images that will "explode" into the expanded RAM and run from RAM. This is already taken care of by the tools. No need to code this. 
Anyway most people assume a 32k real RAM is present. It is common to have both a cartridge and a 32k expansion. The modern memory expansion uses a "sidecar expansion".
This is the most common "target" now for homebrews of the 21st century: 32k memory expansion with a cartridge.

For super small binaries with no bank switching, the code could reside on the cartridge and run from the cartridge. This should be limited to 8k of code + 256 of internal RAM (or +32k if a memory expansion is present).

In the old days (and maybe sometimes even now), the video RAM was also used to store data (and/or even code) but we can avoid this painful process.

**Comment by Fabrizio-Caruso** [comment]
I am looking at:
https://www.unige.ch/medecine/nouspikel/ti99/architec.htm

**Comment by Fabrizio-Caruso** [comment]
I am not sure but it looks like GCC generates a raw ELF binary (relocatable binary?), which is converted supposed to be converted to something a TI99/4A could run by `Elf2Ea5` (which may be relocate it but I am no sure).
In order to store it onto a self-exploding cartridge image it has to be "split" into 8k blocks with `Elf2Ea5`. 
This tool also takes care of prepending the code that reads all the blocks and moves the code onto RAM.

I am looking at: 
https://github.com/jedimatt42/fcmd/wiki/tms9900gcc-Ubuntu-Installation-Guide

**Comment by Fabrizio-Caruso** [comment]
@EtchedPixels I am not sure 100% of all that what I have written. I am trying to use those tools with the binary produced by GCC to see how to use them. Last time I used GCC for TI to do something for the TI was a couple of years.
