### ISSUE TITLE
[info/bug?] How do I build the compiler? make all fails under Windows/Cygwin

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [EtchedPixels/CC6303#3]
I am under Windows/Cygwin.
Can I build CC6303 in this environment.

If I run `make all` I get:
```
...
../as68/as68 _setjmp.s
make[1]: Leaving directory '/cygdrive/c/Retro/CC6303/lib6803'
(cd lib6303; make)
make[1]: Entering directory '/cygdrive/c/Retro/CC6303/lib6303'
../as68/as68 divide.s
../as68/as68 laddeq.s
../as68/as68 lsubeq.s
../as68/as68 tosudivax.s
make[1]: Leaving directory '/cygdrive/c/Retro/CC6303/lib6303'
(cd libio; make)
make[1]: Entering directory '/cygdrive/c/Retro/CC6303/libio'
(cd 6800; make)
make[2]: Entering directory '/cygdrive/c/Retro/CC6303/libio/6800'
make[2]: *** No targets specified and no makefile found.  Stop.
make[2]: Leaving directory '/cygdrive/c/Retro/CC6303/libio/6800'
make[1]: *** [Makefile:2: all] Error 2
make[1]: Leaving directory '/cygdrive/c/Retro/CC6303/libio'
make: *** [Makefile:21: libc] Error 2
```

**Comment by EtchedPixels** [comment]
On Fri, 25 Sep 2020 12:11:13 -0700
Fabrizio Caruso <notifications@github.com> wrote:

> I am under Windows/Cygwin.
> Can I build CC6303 in this environment.
> 
> If I run `make all` I get:


Currently taking a break from the tech stuff but I pushed the missing
makefile quickly so hopefully that sorts it

**Comment by Fabrizio-Caruso** [comment]
Thanks a lot!
I have run  `make all` and `make install`.
It is sort of working because I see the .a files but they may not be in the right directories (e.g., `lib6803.a` is in the repo root directory)

I also see libmc10.a in probably the right place (`target-mc10`).
Does this change the procedure you suggested to build a simple running helloworld example for the mc10 target?
You suggest to use `lib6803:`
```
cc68 -m6803 -c *.c
ld68 -b -C 17500 libc/crt0.o *.o lib6803/lib6803.a -o my.bin
tapeify my.bin my.cas 17500 xxx 17500
where xxx is the length you need for it all to fit.
```

I guess I still need `lib6803` and I will need `libmc10.a` if I want to use `putc`
